### ISSUE TITLE
Character Selection Incompatibility

### ISSUE THREAD

**Issue by smalllbuddy** [prodzpod/RealerCheatUnlocks#1]
This mod doesn't seem compatible with ScrollableLobbyUI. I've opened an issue thread with ScrollableLobbyUI, and I was pointed here. I believe that at one point these mods were compatible, but now it doesn't seem to be the case. When you right click on a locked survivor that isn't on the first page it instead unlocks a survivor that is on the first page. 
[MyProfile.zip](https://github.com/KingEnderBrine/-RoR2-ScrollableLobbyUI/files/14921482/MyProfile.zip)
[LogOutput.log](https://github.com/KingEnderBrine/-RoR2-ScrollableLobbyUI/files/14921503/LogOutput.log)
Here is a short clip showing what happens: [ReproducedError.zip](https://github.com/KingEnderBrine/-RoR2-ScrollableLobbyUI/files/14921544/ReproducedError.zip)

**Comment by Tolstofey** [comment]
I've experienced this issue too, fortunately you can unlock characters and other stuff through the logbook instead

**Comment by prodzpod** [comment]
fixed in 1.0.4

**Comment by smalllbuddy** [comment]
Thanks! Yes, it even works with pre sots if you prefer that.
